import "./globals.css"

// import "../styles/custom.css"
import { ThemeProvider } from "next-themes"
import { AuthProvider } from "@/contexts/auth"
import ErrorBoundary from "@/components/error-boundary"
import Header from "@/components/layout/header"
import Footer from "@/components/layout/footer"
import { Toaster } from "sonner"
// import { NextAuthProviders } from "@/components/auth/auth-provider"
// import { AuthProvider } from "@/contexts/auth"
// import { useThemeConfig } from "@/contexts/theme";

export const metadata = {
  title: "MillionScope",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  // const themeConfig = useThemeConfig()

  return (
    <html lang="en" suppressHydrationWarning dir="ltr">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon/favicon.svg" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <meta name="description" content="MillionScope - Millions of perspectives in one vision." />
        <meta name="author" content="MillionScope" />
        <title>MillionScope - Millions of perspectives in one vision.</title>
      </head>
      <body className="nextra-banner-hidden antialiased h-screen">
        <ErrorBoundary>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <Toaster position="top-center" />
            <AuthProvider>
              <div className="flex h-full w-full flex-col">
                {children}
              </div>
            </AuthProvider>
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  )
}
